id = "mutt"
name = "Mutt"
description = "Syntax highlighting for mutt/neomutt configuration and compose files"
version = "0.2.0"
schema_version = 1
authors = ["Ben Swift"]
repository = "https://github.com/benswift/dotfiles"

[grammars.muttrc]
repository = "https://github.com/benswift/tree-sitter-muttrc"
rev = "173b0ab53a9c07962c9777189c4c70e90f1c1837"

[grammars.mutt_compose]
repository = "https://github.com/benswift/tree-sitter-mutt-compose"
rev = "db2039c17271db0382ee13a74e6d77f1629709ee"