name = "Muttrc"
grammar = "muttrc"
path_suffixes = ["muttrc", "neomuttrc"]
line_comments = ["# "]
tab_size = 2
hard_tabs = false

[file_path_patterns]
patterns = [
  "**/muttrc",
  "**/neomuttrc",
  "**/.muttrc",
  "**/.neomuttrc"
]