id = "mutt-compose"
name = "Mutt Compose"
version = "0.1.0"
schema_version = 1
authors = ["Ben Swift <ben.swift@anu.edu.au>"]
description = "Syntax highlighting for mutt/neomutt compose files"
repository = "file:///Users/ben/.dotfiles/zed/extensions/mutt-compose"

[grammars.mutt_compose]
repository = "file:///Users/ben/.dotfiles/zed/extensions/mutt-compose/grammars/tree-sitter-mutt-compose"